### PR TITLE
fix(frontend): fix responsiveness issues

### LINKED ISSUE #32: Responsiveness of home page
The home page of the website is currently not responsive and gets distorted on small screens:

* [ ] These headings are too big for a small screen, maybe the headings with font size ~3rem would be better for small screens.
  image

* [ ] The last few sections overlap with each other.
  image

### LINKED ISSUE #37: Alignment issue on small screen
The content on small screens is not properly aligned.

* [ ] There seems to be a padding here on the left but not on the right, I think we can remove the padding from the left-side too
  image
* [ ] In the sections below "ABOUT" too, there is padding on the left side while not on the right side. We should fix that too.

### LINKED ISSUE #39: Responsiveness of team page
The team page is not responsive right now and doesn't look good on small screens. This needs to be fixed.

### PR DESCRIPTION
**Pull request by Aksh-Bansal-dev**
fixes #39, fixes #37, fixes #32

### CODE REVIEW

**Comment by Aksh-Bansal-dev** [comment]
@Samy-33, Please review this.

**Comment by garg3133** [comment]
Why aren't the folks from 2021 batch contributing to these? These were really easy issues to get them started.

Also, there's already a PR for #32, shouldn't we help the author of that PR to get it merged?

**Comment by Aksh-Bansal-dev** [comment]
> Why aren't the folks from 2021 batch contributing to these? These were really easy issues to get them started.

I told the 2021 batch to contribute multiple times but there was little to no response. We can't just force them to contribute.

> Also, there's already a PR for https://github.com/BitByte-TPC/TPC-website/issues/32, shouldn't we help the author of that PR to get it merged?

That PR is inactive for the last 10 days.

**Comment by garg3133** [comment]
> I told the 2021 batch to contribute multiple times but there was little to no response. We can't just force them to contribute.

It's not about forcing them to contribute, it's more of a concern that why aren't they participating in these activities, which are going to benefit them the most. Let's discuss about this on Discord.

> That PR is inactive for the last 10 days.

I think we should first ask the author of the PR if they are still interested in working on the issue and if they are not or don't respond in a reasonable amount of time, we can move ahead without that PR.

**Comment by Aksh-Bansal-dev** [comment]
Okay, will remember next time.

**Pull request merged**
