### PR TITLE
Added alumini to the alumni page

### PR DESCRIPTION
**Pull request by Doraemon012**
**Describe the changes you've made**

Added alumni to the alumni page.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

<!-- Please add deployed link to here text >

### CODE REVIEW

**Comment by Pranavg14** [comment]
Sachin Kukreja sir confirmed that he was Co-ordinator of TPC in 2015-16.

**Comment by Tusharjain123** [comment]
@Doraemon012 Also add the details of Sachin Kukreja Sir

**Comment by Doraemon012** [comment]
@Tusharjain123 , @Pranavg14 I've added the details of Sachin Kukreja sir. Please take a look.

**Review by Tusharjain123 — APPROVED** [review]
LGTM

**Pull request merged**
